services:
  db_test:
    image: postgres:16
    container_name: online_library_db_test
    environment:
      POSTGRES_DB: online_library_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d online_library_test"]
      interval: 3s
      timeout: 3s
      retries: 30
    volumes:
      - pg_test_data:/var/lib/postgresql/data

volumes:
  pg_test_data:
